### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SupinePandora43** [Solokiller/HL_Tools#100]
![image](https://user-images.githubusercontent.com/36124472/88179061-bf724180-cc44-11ea-92f4-43af8368bbdc.png)

**Comment by Solokiller** [comment]
You're trying to open a Source engine model. This tool doesn't support that.

**Comment by SupinePandora43** [comment]
oh crap, will you create HL2MV? for source engine?

**Comment by Solokiller** [comment]
No.

**Comment by SupinePandora43** [comment]
**rip**
