### ISSUE TITLE
[Suggestion] Release a "portable version"

### ISSUE THREAD

**Issue by JoelTroch** [Solokiller/HL_Tools#119]
Installers might be great for the majority of users but I think providing a simple "download and extract archive" would be nice too.

**Comment by Solokiller** [comment]
Does that include storing settings next to the installation or is that not required?

**Comment by JoelTroch** [comment]
> 
> 
> Does that include storing settings next to the installation or is that not required?

Ideally, yes.

**Comment by Solokiller** [comment]
I've added a command line parameter `--portable` that will use a local settings file. I'll also provide an archive that can be extracted so as to avoid installer permissions issues.
