### ISSUE TITLE
[Crash] When saving configuration after setting the "Game Install Location"

### ISSUE THREAD

**Issue by JoelTroch** [Solokiller/HL_Tools#121]
When trying to add my Half-Life 1 installation directory and saving the changes, Half-Life: Asset Manager froze for 2 seconds and crashed.

~~I suspect this has to do with the fact that the application is trying to save it's configuration in a "privileged folder" (`C:\Program Files (x86)`) while running with a "standard Windows user account".~~

UPDATE: it crashes even with admin. rights.

**Comment by Solokiller** [comment]
Can you provide the exact steps to take to reproduce this?

**Comment by JoelTroch** [comment]
1. Open the program (ideally without admin. rights and in a "privileged folder" like `C:\Program Files (x86)`).
2. Open the "Options" dialog ("Tools" --> "Options").
3. Go to the "Game Configurations" category.
4. Click the "Add New..." button below the "Game Environments" list.
5. Set the "Game Install Location" value to a Steam Half-Life 1 installation (mine being `D:\Jeux\Steam\steamapps\common\Half-Life`).
6. Hit the "Apply" button and the freeze + crash should happen.

**Comment by Solokiller** [comment]
This should be fixed now.

**Comment by Solokiller** [comment]
Can you test alpha 4 and see if it still happens? If not i can close this issue.

**Comment by JoelTroch** [comment]
It's fixed in Alpha 004, thanks for the fix, closing this issue.
