### ISSUE TITLE
[Suggestion] Add more keyboard shortcuts

### ISSUE THREAD

**Issue by JoelTroch** [Solokiller/HL_Tools#122]
I saw that some keyboard shortcuts such as CTRL+S, CTRL+W and CTRL+Y are assigned to "Save", "Undo" and "Redo" respectively.

How about adding more like "CTRL+O" to "Load" (Open) and CTRL+ALT+S to "Save as" and CTRL+Q to "Quit"?

**Comment by Solokiller** [comment]
They've been added.
