### ISSUE TITLE
Issue with Chrome effect when model is mirrored on the Y axis.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#128]
**Context**

It appears the Chrome effect does not follow the camera's viewpoint when the model is mirrored on the Y axis.

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model with Chrome support e.g. barney.mdl
3. Ensure you see the Chrome effect
4. In 'Model Display' check 'Mirror On Y Axis'
5. Rotate the camera around the model

Expected behavior: Chrome should rotate and follow the camera's viewpoint.
Actual behavior: Chrome appears to rotate in opposite direction.

**Comment by Solokiller** [comment]
This is probably happening because mirroring is done in a way that it also mirrors the viewer right vector. I'll see if i can correct that so that it always stays correct.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha.

I tested with model mirrored on X, Y and Z axis, singularly, and also with all possible combinations:
```
(X,Y), (X,Z), (Y,Z), (X,Y,Z)
```

As this seems to work correctly, I will consider the issue fixed.
