### ISSUE TITLE
Issue with body parts and Render Mode, when Draw Shadows is enabled.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#129]
**Context**

Given a Render Mode different from 'Texture Shaded', and when 'Draw Shadows' is enabled, it appears that every body part except the first one remain textured.

**Tested with**

```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model with multiple body parts e.g. scientist.mdl
3. In 'Model Display' change 'Render Mode' to 'Smooth Shaded'
4. Ensure you see the entire model with Smooth Shaded
5. In 'Model Display' check 'Draw Shadows'
6. Additionally, test with 'Render Mode' set to 'Flat Shaded' and 'Wireframe'

Model used: scientist.mdl

Expected behavior: Head body part should be Smooth Shaded
Actual behavior: Head body part remains textured

**Comment by malortie** [comment]
This possibly happens because textures are enabled at the end of the shadows drawing process.

https://github.com/Solokiller/HL_Tools/blob/597a3a3bdd23daa5eaf2cf32d5c86a5a16cbf16a/src/tools/hlam/engine/renderer/studiomodel/StudioModelRenderer.cpp#L1199-L1203

If so, this would require getting the current texture parameter state before drawing the shadows using `glGetBooleanv(GL_TEXTURE_2D)`.

```cpp
GLboolean oldTexture2d;
glGetBooleanv(GL_TEXTURE_2D, &oldTexture2d);
```

and re-enabling it only if it was enabled before:

```cpp
const auto drawnPolys = InternalDrawShadows(); 

glDepthFunc(GL_LEQUAL); 

if (oldTexture2d)
  glEnable(GL_TEXTURE_2D);
```

**Comment by Solokiller** [comment]
Yeah that seems like it. I'll take a look when i have time and apply the fix.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha.

The issue described above appears to be fixed, but now all bodyparts except the first one appear smooth shaded while rendering in Flat Shading.

This is possibly happening because of `glShadeModel(GL_SMOOTH)` at the end of the function:

https://github.com/Solokiller/HL_Tools/blob/ed46a856a1349a5df4e0d28bd8b23a2cc73d4c6b/src/tools/hlam/engine/renderer/studiomodel/StudioModelRenderer.cpp#L1211-L1215

As this is an alpha build, I am not sure if you prefer me to open a separate issue, or to fix it in the current issue. Please let me know.

**Comment by Solokiller** [comment]
We'll keep it in this issue. I've fixed the bug.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha002

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha 002.

I tested with all rendering modes with 'Draw Shadows' enabled.

It appears to be fixed.
