### ISSUE TITLE
Issue with moving the framerate slider to minimum and maximum values.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#131]
**Context**

When moving the ~'Speed'~ framerate slider slowly to either the minimum or maximum position, the value seems to remain slightly above the minimum (0) and or below the maximum (10) value.

In a series of attempts, I have been unable to slowly move the slider outside the range [0.05, 9.95].

Often, when rapidly moving the slider between the min and max position, it seems to be able to reach the min and max values.

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model that has at least one sequence e.g. scientist.mdl
3. Try to slowly move the ~'Speed'~ framerate slider to the minimum value (0)
4. Try to slowly move the ~'Speed'~ framerate slider to the maximum value (10)

Expected behavior: The minimum (0) and maximum (10) values should be reached.
Actual behavior: The slider does not reach minimum and maximum values.

**Comment by Solokiller** [comment]
You mean the framerate slider, right?

**Comment by malortie** [comment]
Yes.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha. The issue appears to be fixed.
