### ISSUE TITLE
Ground texture does not scroll in the correct direction when model is mirrored.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#134]
**Context**

When the model is mirrored, the ground texture scrolls in the same direction as if the model was not mirrored.

The following part in the code would likely need to be updated to take in account if the model is mirrored along a specific axis.

https://github.com/Solokiller/HL_Tools/blob/597a3a3bdd23daa5eaf2cf32d5c86a5a16cbf16a/src/tools/hlam/graphics/Scene.cpp#L514-L515

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model with at least one sequence that has linear movement e.g scientist.mdl
3. Select the sequence that has linear movement e.g. walk
4. In 'Model Display' check 'Show Ground'
5. Load a ground texture
6. Ensure you see the ground texture scrolling in -X direction
7. In 'Model Display' check 'Mirror On X Axis'

Model used: scientist.mdl

Expected behavior: Ground texture should scroll in +X direction.
Actual behavior: Ground texture scrolls in -X direction.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha. 

I tested with sequences with linear movement along X and Y axis and it appears to work, so it seems fixed.
