### ISSUE TITLE
Unverified entity pointer in Scene.cpp

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#135]
The following code, which gets the `_entity` sequence

https://github.com/Solokiller/HL_Tools/blob/597a3a3bdd23daa5eaf2cf32d5c86a5a16cbf16a/src/tools/hlam/graphics/Scene.cpp#L518-L523

should be moved inside the following block, which checks if `_entity` is valid.

https://github.com/Solokiller/HL_Tools/blob/597a3a3bdd23daa5eaf2cf32d5c86a5a16cbf16a/src/tools/hlam/graphics/Scene.cpp#L494-L516

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
Given that the code has been moved inside the condition that checks that `_entity` pointer is valid, and given that issue https://github.com/Solokiller/HL_Tools/issues/134 is solved, this should be fixed.
