### ISSUE TITLE
Ground back face color is dark when Mirror Model On Ground is enabled.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#137]
**Context**

When 'Mirror Model On Ground' is enabled, the ground back face color turns dark. Is this the intended behavior ?

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model
3. In 'Model Display' check 'Show Ground'
4. Rotate the camera to see the ground back face
5. In 'Model Display' check 'Mirror Model On Ground'

Expected behavior: Ground back face color should remain the same as the front face color ?
Actual behavior: Ground back face color is dark.

**Comment by Solokiller** [comment]
This is intended behavior, carried over from Jed's Model Viewer.
