### ISSUE TITLE
Issue with Player Hitbox blending.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#138]
**Context**

Depending on the viewpoint, several faces of the player hitbox appear to blend on top of others.

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.0.0
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model
3. In 'Model Display' check 'Show Player Hitbox'
4. Rotate the camera and do a full turn around the model

Expected behavior: Each player hitbox face should not blend with each other.
Actual behavior: Several faces appear to blend on top of others.

**Comment by Solokiller** [comment]
I've provided an alpha build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha001

**Comment by malortie** [comment]
I'm on it.

**Comment by malortie** [comment]
I tested with the 1.1.0 alpha. The issue appears to be fixed.
