### ISSUE TITLE
About message box does not display the correct release version.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#140]
For alpha builds and future releases, the version shown in the about message box should probably correspond to the release.

https://github.com/Solokiller/HL_Tools/blob/ebd076f2591cfae5495d8e453d9cf51d54efbfe5/src/tools/hlam/ui/MainWindow.cpp#L529-L530

In HLAM-V1.1.0-alpha002, it shows `Half-Life Asset Manager 1.0.0`.

**Comment by Solokiller** [comment]
Yeah i know i need to set up a script to pull the latest tag for use in that box.

**Comment by malortie** [comment]
Should I close the issue ?

**Comment by Solokiller** [comment]
No i'll close it when i've set up a script.

**Comment by Solokiller** [comment]
Version number and Git information is now included in the About dialog. The version number is based on the CMakeLists value instead of being hard-coded in the dialog code.
