### ISSUE TITLE
[Optimization] Calculate bone adjustment only when bone controller value changed.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#141]
The bone adjustment values are calculated each time the model is drawn.

https://github.com/Solokiller/HL_Tools/blob/9e3f3aa10946c1217450967fe8f8f37beee0b9f0/src/tools/hlam/engine/renderer/studiomodel/StudioModelRenderer.cpp#L695-L703

https://github.com/Solokiller/HL_Tools/blob/9e3f3aa10946c1217450967fe8f8f37beee0b9f0/src/tools/hlam/engine/renderer/studiomodel/StudioModelRenderer.cpp#L752-L764

The call to `CalcBoneAdj()` could be moved at the end of [StudioModelEntity::SetController](https://github.com/Solokiller/HL_Tools/blob/9e3f3aa10946c1217450967fe8f8f37beee0b9f0/src/tools/hlam/game/entity/StudioModelEntity.cpp#L443-L445) and calculate the adjustment when the bone controller value changes.

e.g.

```cpp
setting = std::clamp(setting, 0, 255);

_controller[controller] = setting;

GetContext()->StudioModelRenderer->CalcBoneAdj(controller, setting);
```

This could also be done for the mouth controller in [StudioModelEntity::SetMouth](https://github.com/Solokiller/HL_Tools/blob/9e3f3aa10946c1217450967fe8f8f37beee0b9f0/src/tools/hlam/game/entity/StudioModelEntity.cpp#L505-L507).

**Comment by Solokiller** [comment]
This is intentional. The code for bone setup is supposed to be shared between multiple entities so those variables would be changed multiple times in a single frame. In the future when map support is added this kind of optimization won't work.
