### ISSUE TITLE
Show Player Hitbox option causes model to render under the ground when model is mirrored.

### ISSUE THREAD

**Issue by malortie** [Solokiller/HL_Tools#144]
**Context**

It appears enabling 'Show Player Hitbox' option when 'Mirror Model On Ground' is enabled causes the model to render under the ground.

**Tested with**
```
Software: Half-Life Asset Manager
Version: 1.1.0 Alpha 005
OS: Microsoft Windows 10 Home
```

**Steps to reproduce**

1. Launch Half-Life Asset Manager
2. Load a model e.g. scientist.mdl
3. In 'Model Display' check 'Show Ground' 
4. In 'Model Display' check 'Mirror Model On Ground' 
5. Rotate the camera to view under the ground
6. In 'Model Display' check 'Show Player Hitbox' 

Expected behavior: Model should not render under the ground.
Actual behavior: Model renders under the ground.

**Comment by Solokiller** [comment]
I've provided a beta build that fixes this issue. Can you test it and see if it's fixed?

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-beta001

**Comment by malortie** [comment]
I tested with the 1.1.0 beta 001. The issue appears to be fixed.
