### ISSUE TITLE
Couldn't opening some of them model files

### ISSUE THREAD

**Issue by longlong2002** [Solokiller/HL_Tools#152]
GFL_M4_Sopmod-c2 
cannot open with HLAM/HLMV2.0

**Comment by Solokiller** [comment]
The problem is that the model has a remapped texture with an incorrect index value. I'll make sure this can't crash the program anymore.

**Comment by Solokiller** [comment]
I've released a beta build that fixes this: https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.2.0-beta001

Can you test this to verify that it's fixed?
