### ISSUE TITLE
[HLMV] Reload model data if F5 is pressed

### ISSUE THREAD

**Issue by Solokiller** [Solokiller/HL_Tools#26]

**Comment by SPRKH** [comment]
Big bump, but as an animator who does a lot of recompiling this feature alone would save so many clicks it's not even funny. Pretty please?

**Comment by Solokiller** [comment]
This is now implemented, but reloading also resets viewer state. Implementing state saving and loading is too difficult for the 2.x version of HLMV, but version 3 will support that.
