### ISSUE TITLE
[HLMV enhancement] Hitbox editing visualisation.

### ISSUE THREAD

**Issue by Gazyi** [Solokiller/HL_Tools#36]
Sometimes it's problematic to calculate hitboxes even after tweaking and recompile over 9000 times. It'll be useful if model viewer will have a visualisation for creating and editing hitboxes, like constraints limits editing in Source HLMV, where you can change numbers on the go then export constraints limits in text file.  But model can have many hitboxes with same origin bone, that can be a problem. Is it possible?

**Comment by SamVanheer** [comment]
The file format is structured in a manner that would allow the hitboxes to be resized at will. Creating new hitboxes isn't so easy due to how it stores them, and the current implementation would need to be rewritten to allow for that.

**Comment by Solokiller** [comment]
Hitbox editing has been added to the current pre-release build. You can select a hitbox from the list and edit its data. See the new Hitbox control panel for this feature.
