### ISSUE TITLE
Where are the resources?

### ISSUE THREAD

**Issue by BitSums** [Solokiller/HL_Tools#37]
Add all of the resources. You tried to compile from scratch that is on the round?
Not missing a hell of a lot of things.

**Comment by SamVanheer** [comment]
Are you referring to the third party libraries? I excluded them from the repository, seeing as they take up a fairly large amount of space. If it's necessary, i can include them as well.

**Comment by BitSums** [comment]
Please add at least a description file.
I'm tired all over the internet to gather resources for the compilation.

**Comment by SamVanheer** [comment]
The information covering external libraries can be found on the wiki: https://github.com/SamVanheer/HL_Tools/wiki/External-libraries

**Comment by BitSums** [comment]
I do not need the information ... you attach the file.
The information the compiler gives me so I can see what libraries are required.

**Comment by SamVanheer** [comment]
I've added links to websites and downloads for each library to the wiki page.
