### ISSUE TITLE
[HLMV] Default View Origin and active tab

### ISSUE THREAD

**Issue by SPRKH** [Solokiller/HL_Tools#39]
The option to set the default View Origin to either Free View or Weapon Origin would be a useful addition. This, combined the ability to select which tab should be active on startup (ie. Textures or Sequences, rather than Model Display), would save animators a lot of clicks in the long run (at least until model refreshing is implemented).

**Comment by SamVanheer** [comment]
I'll add the options to the Options menu.

**Comment by SPRKH** [comment]
It just occurred to me that a perhaps more elegant way would be remembering the active tabs on shutdown, and restoring them on startup.

**Comment by Solokiller** [comment]
The current camera and control panel are now saved and restored.
