### ISSUE TITLE
Feature Request: Export Textures/UV Enhancements

### ISSUE THREAD

**Issue by ParaBolt** [Solokiller/HL_Tools#51]
1. It would be very helpful if the export dialog set the filename to be the name of the currently selected texture. Eg. if I am viewing mesh1.bmp; when I click on Export, it will show mesh1.bmp on the dialog box rather than an empty field.

2. An export all feature would be really useful, if possible to make.

**Comment by ParaBolt** [comment]
Hi, any updates? Are you planning to add this?

**Comment by Solokiller** [comment]
I've added these requests, you can check them out in the current pre-release build.
