### ISSUE TITLE
Feature Request: Associate file types/Window startup state in Options

### ISSUE THREAD

**Issue by i486** [Solokiller/HL_Tools#53]
1. Some option to associate *.mdl, etc files in HLMV options dialog.
2. Remember windows size or something like that in options. It currently always starts maximized.

Great tool!

**Comment by y2keeth** [comment]
2nd that one

**Comment by Solokiller** [comment]
For file type associations i'll need to create an installer, that'll be done for version 3. For future reference (for myself mostly), the documentation regarding the adding of file associations can be found here: https://doc.qt.io/qtinstallerframework/qt-installer-framework-registerfileextension-example.html

I'll see if i can implement window size saving and loading.

**Comment by Solokiller** [comment]
Window position, size and whether it's maximized are now saved and restored.

**Comment by Solokiller** [comment]
Issue #91 is tracking the installer requirements, so i'm closing this issue as the window properties request has been implemented. See that issue for progress on file associations support.
