### ISSUE TITLE
[HLMV] Support Windows program folders

### ISSUE THREAD

**Issue by LogicAndTrick** [Solokiller/HL_Tools#54]
If I install HLMV into `C:\Program Files`, it crashes on startup, probably because the folder isn't writable with default permissions. Could HLMV use an AppData folder to save its settings if the current folder isn't writable?

**Comment by SamVanheer** [comment]
I will keep this in mind when designing the new model viewer. I've added it to the new project tracker: https://github.com/SamVanheer/SharpLife-Engine/projects/4#card-13284258

**Comment by Solokiller** [comment]
HLMV 3 uses QSettings to save and load settings.

The documentation for QSettings explains where settings are stored:
https://doc.qt.io/qt-5/qsettings.html#locations-where-application-settings-are-stored

HLMV 3 uses the ini file format, so this is where settings are stored:
Windows XP: `\Documents and Settings\$USER$\Application Data\Half-Life Model Viewer\Half-Life Model Viewer.ini`
Windows Vista and newer: `\Users\$USER$\AppData\Roaming\Half-Life Model Viewer\Half-Life Model Viewer.ini`

All future settings will be accessed through QSettings. If settings need to be stored next to the program installation then this can also be done using QSettings. To ensure that the program can access and write to these files, the installer will have to set up permissions for the install directories to allow for this.

See #91 for installer related requirements.

**Comment by LogicAndTrick** [comment]
Please only alter the permissions of the install directory if a "portable installation" is requested by the user during install. Granting non-UAC write access to the install directory is bad practice.

**Comment by Solokiller** [comment]
I've updated #91 to account for that.

**Comment by Solokiller** [comment]
Reopening due to project restructuring.

**Comment by Solokiller** [comment]
This has been implemented. Settings are saved and loaded from the paths listed above. Writable program-wide settings could also be saved in the ProgramData directory so there won't be any need to make the installation directory writable if such settings become necessary in the future.
