### ISSUE TITLE
[Feature Request] Toggle Option to Invert drag controls.

### ISSUE THREAD

**Issue by PRinceBhai** [Solokiller/HL_Tools#60]
I've noticed that this particular hlmv, have inverted controls for Dragging the camera across the model, which infact really triggers me to be not being able to restore it to originals like other model viewer or editor programs. I don't know if it's much to do but'll be very happy if this is implemented.

**Comment by SamVanheer** [comment]
I'll add an option to invert the pitch and yaw for all cameras.

**Comment by PRinceBhai** [comment]
@SamVanheer Any ETA?

**Comment by Solokiller** [comment]
This has been implemented in the current pre-release build. Check the Options menu for the settings.

**Comment by PRinceBhai** [comment]
@Solokiller Hi, Sorry i'm using this Issue again, but i tested this when you closed this issue. But couldn't reply here for some reason. I actually meant to Have an Option to Invert the "Drag of the Model", by that i mean when you "Shift+Mouse 1" and Move the Cursor to left the model should go left but it goes to Right. That's what i meant not the View Pan/Drag. I'm sorry if i made this more confusing. Please let me know if i need to elaborate further. Thanks for time tho.

**Comment by Solokiller** [comment]
I've fixed the default dragging directions and i've made the options to invert dragging directions apply to translation as well.
