### ISSUE TITLE
Can't open the program

### ISSUE THREAD

**Issue by gloeyisk** [Solokiller/HL_Tools#62]
Currently I'm using the latest build of these program but whenever I open it, the program keeps showing error. Screenshot attached.

![Untitled](https://user-images.githubusercontent.com/43908341/65778915-fd135480-e170-11e9-8ab9-326c57835271.png)

**Comment by SamVanheer** [comment]
I don't know what could cause that, but this article may be able to help you out: https://www.techadvisor.co.uk/how-to/windows/application-error-0xc000007b-3613164/

**Comment by Solokiller** [comment]
Do you still need any help? If so, try the current pre-release build. If that doesn't work, please provide the following information:
* OS version
* OpenGL version supported by your computer
