### ISSUE TITLE
[HLMV] Add player size reference

### ISSUE THREAD

**Issue by regener** [Solokiller/HL_Tools#63]
Can I request a player model size reference to with a toggle on/off option?
For example if I load a tree it would be helpful to see how tall would it be in the game.

**Comment by SamVanheer** [comment]
I'll add a way to view the size in units.

**Comment by Solokiller** [comment]
I've added an option to draw a transparent green box that shows the player hitbox (32x32x72).

Note that it is drawn the way a player's hitbox would be standing on the ground. Player models have their origin in the middle of the model so they'll be stuck halfway in the ground. NPC models should align properly.

Check the current pre-release build if you want to try it out.
