### ISSUE TITLE
Version Differs Error

### ISSUE THREAD

**Issue by im-richard** [Solokiller/HL_Tools#64]
Every model opened seems to return a 'version differs' error. Is their a documented solution for this or any idea of a work-around? Tried multiple models thinking it was maybe how the particular model was compiled, but it seems every model has the issue.

**Comment by 9268** [comment]
same issues,why?

**Comment by Solokiller** [comment]
Can you give me some models to check and see what's wrong?

**Comment by Solokiller** [comment]
I've improved error reporting for when models fail to load, there's a pre-release alpha build available if you want to try it: https://github.com/Solokiller/HL_Tools/releases/tag/v2.9-alpha

**Comment by Solokiller** [comment]
If you still encounter issues, please reply to this issue with models to test with so i can reopen it and investigate.

**Comment by im-richard** [comment]
So I can upload the models somewhere if need-be. I just got back to trying this and the same issue occurs for any of the models I'm trying to load. Mostly models from the steam workshop that were downloaded using the steam workshop downloader. 

All of them say "Version differs, expected '10', returned '44'
And sometimes it says "returned '48'"

**Comment by Solokiller** [comment]
This model viewer only supports version 10, which are GoldSource models. Version 44 and higher are Source engine models, which this model viewer does not support.
