### ISSUE TITLE
add support & creation of res files 

### ISSUE THREAD

**Issue by sixcentgeorge** [Solokiller/HL_Tools#65]
this tool is quite cool and well made .. [if only it was able to read idtech4 models...]
one thing is missing , [ i joke.. but you wrote hl_toolS ] ;
the support of the res files..you know like me that ripenting is an easy way to add monsters or monsters to map .. the problem is the precaching of sounds...[ that has to be also well programmed in the dlls of mods.. ]
so using the so good and famous code from resgen : https://github.com/kriswema/resgen
you could add the wav from models to the list of the map res.. as well as the sounds that are used from the sentences.txt and materials.txt files...
that look like : // DECAY DOORS
CROSSDOOR doctor cross access granted
GREENDOOR doctor green access granted
GREENDOOR2 doctor green access denied

when i did my own edition for playing svencoop "quietly & peacefully" using version 4.7 ; i had a lot of work creating this files : materials and sentences .txt .. 
by now i am trying to create something bigger that has nearly 200 maps [ may be more if i cam use a lot of models and models : without fearing the 512 limit or the max files list loading limit a server can handle...] so that could be great if your tools were also able to check the sounds used by mods , maps and models to generate new "optimized" sentences and materials files . may be with a list of files that are not included in these files.. and so that mean "re-editing" the maps entity file or map or rmf to replace the "sentence" with the wav filenames ..
[for me that seems clear ..like water ]
i am searching help to create the dlls of my latest project...: you seem to be the man able to make the dlls or even the halflife for it..
read https://www.moddb.com/mods/sandpit/page/2#comments and page one to learn more ..  
i need something looking like opposing force/svencoop with few more monsters [ like the race alien and robots from sweet half life ] plus the ability to play in mode dual players or four players .. mostly for the game to be like in mods azure sheep or decay : with two players but also two aliens .. like the kingpin or the king tor .. [ or console like style with 4 players 2x2 or 4x1]  i am open to try to port this to unreal 4 engine.. for better rendering..and technical possibilities .

**Comment by Solokiller** [comment]
As i said in the other issue i don't get involved in specific mods' development.

What you're asking is to make a tool that has to have mod-specific resgen support, since some mods have different ways of handling these files. You should direct your request to the authors of these mods.

I don't have any plans to create such a tool, and this repository only covers HLMV now so i'm going to close this issue.
