### ISSUE TITLE
The scrollbars are way too big

### ISSUE THREAD

**Issue by CS-PRO1** [Solokiller/HL_Tools#67]
![Untitled](https://user-images.githubusercontent.com/50755959/76217783-b8a9db80-621b-11ea-86da-41f5cba7638a.png)
As per title.. It's kinda frustrating as it blocks some buttons
Resolution is 1366x768

**Comment by Solokiller** [comment]
There is no way to change the size of the scrollbars so you'll have to scroll it if you want to see everything. I'll see if i can provide some way to change the height of the control panel area to eliminate the vertical scrollbar instead.

**Comment by Solokiller** [comment]
I've updated the pre-release build with a change that forces the control panel area to be large enough to avoid creating vertical scrollbars. It'll use a little more vertical space but it should avoid this issue from now on.

**Comment by CS-PRO1** [comment]
Great! Thank you, I tried it and it's much better now. Tho I suggest keeping it optional or at least manually adjustable for those who may prefer a bigger model viewing space..

**Comment by Solokiller** [comment]
I've improved the layout for all control panels to reduce their vertical size as much as possible. All control panels are smaller than the main panel on the left hand side so the forced minimum size is no longer required. You can check the current pre-release to see how it works now.
