### ISSUE TITLE
Crash when trying to set transparent flag

### ISSUE THREAD

**Issue by GarompaEstomper** [Solokiller/HL_Tools#95]
No matter the texture, when clicking on the Transparent flag of any texture in a GoldSRC .mdl, the software closes without any error message.

I have tested that the problem is not related to the model using previous versions and other different viewers and the transparency flag works just fine with those.

**Comment by Solokiller** [comment]
I can't reproduce any crash using the current beta.

Can you try using the "Import Texture" feature on a texture to see if that also crashes? That would help identify the cause.

**Comment by Solokiller** [comment]
I've fixed this issue, you can test it in the newest beta build.
